#!/usr/bin/env python3
"""Static audit of data/dbc/*.dbc: duplicates, orphan references, size, tier.
Writes DBC_AUDIT.md in the repo root (not in data/, which is flashed to the device). Tiers are a heuristic by file name only; they
say nothing about licence or about which market a file really targets."""
import hashlib, os, re, sys

D = os.path.join(os.path.dirname(__file__), "..", "data", "dbc")
SPECIALIZED = re.compile(r"(object|radar|adas|actuator|park_assist|party|lowspeed|chassis|"
                         r"high_voltage|body|ESR|CADS|_exp|dsu|tssp)", re.I)
ESSENTIAL = re.compile(r"(psa_|hyundai|toyota_(2017|prius|iQ)|nissan|mazda_(2017|3)|"
                       r"mg\.|hongqi|gwm|luxgen|vw_(mqb|pq)\b|vw_mqb\.)", re.I)

def tier(n):
    if SPECIALIZED.search(n): return "specialized"
    if ESSENTIAL.search(n): return "essential"
    return "supplemental"

rows, hashes, problems = [], {}, 0
for f in sorted(os.listdir(D)):
    if not f.lower().endswith(".dbc"): continue
    raw = open(os.path.join(D, f), "rb").read()
    t = raw.decode("latin-1")
    ids = re.findall(r"^BO_ (\d+) ", t, re.M)
    known = set(ids)
    orphan = len({m for m in re.findall(r"^(?:VAL_|CM_ SG_) (\d+) ", t, re.M) if m not in known})
    dupid = len(ids) - len(known)
    h = hashlib.md5(raw).hexdigest()
    same = hashes.setdefault(h, f)
    if same != f: problems += 1
    if dupid: problems += 1
    rows.append((f, len(raw), len(ids), orphan, dupid, tier(f), same if same != f else ""))

out = ["# DBC audit (generated by scripts/audit_dbc.py)", "",
       "Tier is a name-based heuristic. Source and licence of each file are NOT",
       "verified; see THIRD_PARTY_NOTICES.md. Orphan = comment/value-table rows that",
       "point to a message id missing from the same file (harmless, not parsed).", "",
       "| File | Bytes | Messages | Orphan refs | Dup ids | Tier | Duplicate of |",
       "|---|---|---|---|---|---|---|"]
out += ["| " + " | ".join(map(str, r)) + " |" for r in rows]
open(os.path.join(os.path.dirname(__file__), "..", "DBC_AUDIT.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"{len(rows)} files, {problems} hard problems")
sys.exit(1 if problems else 0)
